resources:
  containers:
  - container: pi-gen
    image: wpilib/pi-gen:latest
    options: --privileged --cap-add=MKNOD

jobs:
 - job: 'Main'
   pool: RoboRioConnections
   workspace:
      clean: false # Clean fails because the agent cannot remove files created by root
   timeoutInMinutes: 0
   container: pi-gen

   steps:
      - script: |
          sudo rm -rf $(Build.SourcesDirectory) $(Build.BinariesDirectory)
        displayName: 'Clean Workspace'
      - checkout: self
        submodules: true
      - script: |
          sudo sh -c 'dpkg-reconfigure qemu-user-static && ./build.sh'
          cp deploy/*.zip deploy/examples/*.zip $BUILD_ARTIFACTSTAGINGDIRECTORY
        displayName: 'Build Image'
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'FRCVisionImage'
